# Generated by Django 4.1 on 2023-03-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("primary_care", "Primary Care"),
                            ("pediatrics", "Pediatrics"),
                            ("internal_medicine", "Internal Medicine"),
                            ("cardiology", "Cardiology"),
                            ("neurology", "Neurology"),
                            ("ob_gyn", "Obstetrics and Gynecology"),
                            ("orthopedics", "Orthopedics"),
                            ("dermatology", "Dermatology"),
                        ],
                        max_length=255,
                    ),
                ),
                ("specialization", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("bio", models.TextField()),
                (
                    "photo",
                    models.ImageField(
                        default="static/img/avatar.png", upload_to="doctors/"
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
    ]
