# Generated by Django 4.1 on 2023-03-20 20:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="affiliation",
                    ),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="external link"
                    ),
                ),
                ("published_date", models.DateTimeField(verbose_name="date published")),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                ("news_content", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "cover_img",
                    models.ImageField(upload_to="news/", verbose_name="cover image"),
                ),
                (
                    "is_publish",
                    models.BooleanField(default=True, verbose_name="publish"),
                ),
            ],
        ),
    ]
